// Snapshot of the Subway UK menu, captured by hand. This is a point-in-time
// copy: it can (and will) go stale as Subway changes its menu or reformulates
// items. Re-capture from Subway's published nutrition data to refresh.
export default [
    {
        name: 'Sub_Bacon',
        calories: 306,
        fat: 11,
        saturated: 4.2,
        carbs: 37,
        sugars: 5.1,
        fibre: 2.3,
        protein: 16,
        salt: 1.5
    },
    {
        name: 'Sub_Poached_Egg_and_Cheese',
        calories: 294,
        fat: 9.1,
        saturated: 3.4,
        carbs: 37,
        sugars: 4.7,
        fibre: 2.5,
        protein: 16,
        salt: 1
    },
    {
        name: 'Sub_Lincolnshire_Sausage',
        calories: 353,
        fat: 15,
        saturated: 5.6,
        carbs: 39,
        sugars: 4.8,
        fibre: 2.6,
        protein: 16,
        salt: 1.6
    },
    {
        name: 'Sub_Poached_Egg_and_Guacamole',
        calories: 380,
        fat: 19,
        saturated: 4.9,
        carbs: 39,
        sugars: 5.3,
        fibre: 3.5,
        protein: 23,
        salt: 1.4
    },
    {
        name: 'Sub_Lincolnshire_Sausage_and_Bacon',
        calories: 446,
        fat: 21,
        saturated: 8.7,
        carbs: 43,
        sugars: 8.7,
        fibre: 2.7,
        protein: 22,
        salt: 2.4
    },
    {
        name: 'Sub_Big_Breakwich',
        calories: 599,
        fat: 30,
        saturated: 10,
        carbs: 55,
        sugars: 9.4,
        fibre: 4.2,
        protein: 30,
        salt: 3
    },
    {
        name: 'Sub_Big_Bombay',
        calories: 565,
        fat: 14,
        saturated: 5,
        carbs: 80,
        sugars: 41,
        fibre: 4.2,
        protein: 30,
        salt: 2.6
    },
    {
        name: 'Sub_Chicken_Breast',
        calories: 340,
        fat: 6.8,
        saturated: 3.1,
        carbs: 42,
        sugars: 7,
        fibre: 2.4,
        protein: 26,
        salt: 1.8
    },
    {
        name: 'Sub_Chicken_Tikka',
        calories: 345,
        fat: 7.1,
        saturated: 2.9,
        carbs: 43,
        sugars: 6.4,
        fibre: 3.5,
        protein: 28,
        salt: 1.5
    },
    {
        name: 'Sub_Furious_Chicken',
        calories: 520,
        fat: 24,
        saturated: 5.8,
        carbs: 49,
        sugars: 7.2,
        fibre: 4.5,
        protein: 26,
        salt: 2.5
    },
    {
        name: 'Sub_Rotisserie_Style_Chicken',
        calories: 310,
        fat: 7.6,
        saturated: 2.5,
        carbs: 38,
        sugars: 5.6,
        fibre: 2.5,
        protein: 22,
        salt: 1.4
    },
    {
        name: 'Sub_Tex_Mexan',
        calories: 386,
        fat: 23,
        saturated: 6.2,
        carbs: 18,
        sugars: 7.5,
        fibre: 3.8,
        protein: 26,
        salt: 2.1
    },
    {
        name: 'Sub_Honey_Mustard_BBQ_Chicken_And_Bacon',
        calories: 430,
        fat: 15,
        saturated: 5.7,
        carbs: 44,
        sugars: 12,
        fibre: 3.5,
        protein: 28,
        salt: 2.4
    },
    {
        name: 'Sub_Rotisserie_Style_Chicken_and_Guacamole',
        calories: 469,
        fat: 25,
        saturated: 6.3,
        carbs: 43,
        sugars: 8.3,
        fibre: 3.8,
        protein: 26,
        salt: 2.2
    },
    {
        name: 'Sub_Meatball_Marinara_Pork_And_Beef_Meatballs',
        calories: 447,
        fat: 16,
        saturated: 5.7,
        carbs: 51,
        sugars: 12,
        fibre: 5.2,
        protein: 23,
        salt: 1.9
    },
    {
        name: 'Sub_Philly_Steak',
        calories: 297,
        fat: 3.6,
        saturated: 0.8,
        carbs: 48,
        sugars: 8.9,
        fibre: 3,
        protein: 18,
        salt: 1.3
    },
    {
        name: 'Sub_The_Baller',
        calories: 531,
        fat: 25,
        saturated: 8.5,
        carbs: 56,
        sugars: 12,
        fibre: 5,
        protein: 25,
        salt: 2.7
    },
    {
        name: 'Sub_Taco_Beef',
        calories: 353,
        fat: 12.0,
        saturated: 5.0,
        carbs: 44,
        sugars: 6.0,
        fibre: 3.8,
        protein: 15.0,
        salt: 1.5
    },
    {
        name: 'Sub_Mexicana_Beef_Crunch',
        calories: 525,
        fat: 29,
        saturated: 8.2,
        carbs: 54,
        sugars: 7.9,
        fibre: 5.5,
        protein: 19,
        salt: 2.7
    },
    {
        name: 'Sub_Garlic_Cheesesteak',
        calories: 539,
        fat: 27,
        saturated: 6.7,
        carbs: 51,
        sugars: 12,
        fibre: 4.1,
        protein: 24,
        salt: 2.2
    },
    {
        name: 'Sub_Legendary_Teriyaki',
        calories: 440,
        fat: 13,
        saturated: 5.8,
        carbs: 50,
        sugars: 14,
        fibre: 2.9,
        protein: 29,
        salt: 2.6
    },
    {
        name: 'Sub_Ham',
        calories: 324,
        fat: 7.9,
        saturated: 3.2,
        carbs: 42,
        sugars: 6.4,
        fibre: 3,
        protein: 21,
        salt: 1.8
    },
    {
        name: 'Sub_Turkey',
        calories: 312,
        fat: 6.6,
        saturated: 2.8,
        carbs: 41,
        sugars: 6.1,
        fibre: 2.7,
        protein: 22,
        salt: 1.8
    },
    {
        name: 'Sub_Ham_and_Turkey',
        calories: 327,
        fat: 7.4,
        saturated: 3,
        carbs: 42,
        sugars: 6.3,
        fibre: 2.9,
        protein: 23,
        salt: 2.0
    },
    {
        name: 'Sub_Spicy_Italian',
        calories: 498,
        fat: 27,
        saturated: 10,
        carbs: 43,
        sugars: 5.7,
        fibre: 2.7,
        protein: 22,
        salt: 3.2
    },
    {
        name: 'Sub_Italian_B.M.T',
        calories: 386,
        fat: 16,
        saturated: 5.2,
        carbs: 41,
        sugars: 4.8,
        fibre: 2.5,
        protein: 20,
        salt: 2.5
    },
    {
        name: 'Sub_Notorious_B.M.T',
        calories: 479,
        fat: 25,
        saturated: 7.4,
        carbs: 41,
        sugars: 7.5,
        fibre: 3.5,
        protein: 23,
        salt: 3
    },
    {
        name: 'Sub_Veggie_Delite',
        calories: 227,
        fat: 2.4,
        saturated: 0.5,
        carbs: 42,
        sugars: 6.6,
        fibre: 3.2,
        protein: 8.3,
        salt: 0.6
    },
    {
        name: 'Sub_Cheese_and_Guacamole',
        calories: 310,
        fat: 17,
        saturated: 2.9,
        carbs: 38,
        sugars: 5.7,
        fibre: 2.8,
        protein: 10,
        salt: 1.3
    },
    {
        name: 'Sub_Tuna_Mayonaise',
        calories: 400,
        fat: 16,
        saturated: 3.4,
        carbs: 43,
        sugars: 6.6,
        fibre: 2.4,
        protein: 22,
        salt: 1.8
    },
    {
        name: 'Sub_Ulitmate_Festive',
        calories: 449,
        fat: 16,
        saturated: 5.4,
        carbs: 49,
        sugars: 10,
        fibre: 3.9,
        protein: 26,
        salt: 2.2
    },
    {
        name: 'Toastie_Honey_Mustard_Deli_Toastie',
        calories: 362,
        fat: 12,
        saturated: 4.8,
        carbs: 41,
        sugars: 8.5,
        fibre: 3,
        protein: 21,
        salt: 2.1
    },
    {
        name: 'Toastie_Bacon_and_Cheese_Toastie',
        calories: 487,
        fat: 24,
        saturated: 10,
        carbs: 43,
        sugars: 11,
        fibre: 2.6,
        protein: 27,
        salt: 3
    },
    {
        name: 'Toastie_Big_Cheesesteak_Toastie',
        calories: 458,
        fat: 18,
        saturated: 6.6,
        carbs: 48,
        sugars: 11,
        fibre: 3.3,
        protein: 26,
        salt: 2
    },
    {
        name: 'Toastie_Triple_Cheese',
        calories: 345,
        fat: 13,
        saturated: 6.5,
        carbs: 44,
        sugars: 11,
        fibre: 2.5,
        protein: 14,
        salt: 1.5
    },
    {
        name: 'Toastie_BBQ_Chicken_And_Bacon_Toastie',
        calories: 410,
        fat: 14,
        saturated: 5.6,
        carbs: 43,
        sugars: 10,
        fibre: 2.8,
        protein: 27,
        salt: 2.4
    },
    {
        name: 'Super_Sub_Nacho_Chicken',
        calories: 423,
        fat: 17,
        saturated: 3.4,
        carbs: 49,
        sugars: 7,
        fibre: 3.5,
        protein: 18,
        salt: 1.9
    },
    {
        name: 'Super_Sub_Ham_and_Cheese',
        calories: 380,
        fat: 16,
        saturated: 5.2,
        carbs: 39,
        sugars: 6.3,
        fibre: 2.7,
        protein: 20,
        salt: 2.1
    },
    {
        name: 'Super_Sub_BLT',
        calories: 317,
        fat: 13,
        saturated: 2.4,
        carbs: 38,
        sugars: 6.3,
        fibre: 2.9,
        protein: 14,
        salt: 1.5
    },
    {
        name: 'Wrap_Big_Breakwich',
        calories: 685,
        fat: 33,
        saturated: 11.0,
        carbs: 67,
        sugars: 7.8,
        fibre: 6,
        protein: 29,
        salt: 3.6
    },
    {
        name: 'Wrap_Big_Bombay',
        calories: 500,
        fat: 17,
        saturated: 5.7,
        carbs: 55,
        sugars: 8.3,
        fibre: 5.6,
        protein: 29,
        salt: 2.7
    },
    {
        name: 'Wrap_Chicken_Breast',
        calories: 410,
        fat: 10,
        saturated: 3.4,
        carbs: 51,
        sugars: 5.3,
        fibre: 4.3,
        protein: 25,
        salt: 2.3
    },
    {
        name: 'Wrap_Chicken_Tikka',
        calories: 414,
        fat: 11,
        saturated: 3.3,
        carbs: 51,
        sugars: 4.7,
        fibre: 5.4,
        protein: 27,
        salt: 2.1
    },
    {
        name: 'Wrap_Furious_Chicken',
        calories: 606,
        fat: 27,
        saturated: 6.5,
        carbs: 61,
        sugars: 5.5,
        fibre: 6.3,
        protein: 25,
        salt: 3.2
    },
    {
        name: 'Wrap_Rotisserie_Style_Chicken',
        calories: 354,
        fat: 7.7,
        saturated: 1.1,
        carbs: 49,
        sugars: 3.6,
        fibre: 4.3,
        protein: 19,
        salt: 1.7
    },
    {
        name: 'Wrap_Tex_Mexan',
        calories: 582,
        fat: 22,
        saturated: 6.3,
        carbs: 62,
        sugars: 7.6,
        fibre: 5.9,
        protein: 31,
        salt: 2.9
    },
    {
        name: 'Wrap_The_Baller',
        calories: 650,
        fat: 32,
        saturated: 11,
        carbs: 68,
        sugars: 9.9,
        fibre: 6.8,
        protein: 27,
        salt: 3.5
    },
    {
        name: 'Wrap_Honey_Mustard_BBQ_Chicken_And_Bacon',
        calories: 516,
        fat: 19,
        saturated: 6.5,
        carbs: 56,
        sugars: 9.9,
        fibre: 5.3,
        protein: 28,
        salt: 3
    },
    {
        name: 'Wrap_Rotisserie_Style_Chicken_and_Guacamole',
        calories: 555,
        fat: 29,
        saturated: 7.1,
        carbs: 55,
        sugars: 6.7,
        fibre: 5.6,
        protein: 25,
        salt: 2.8
    },
    {
        name: 'Wrap_Meatball_Marinara_Pork_And_Beef_Meatballs',
        calories: 474,
        fat: 16,
        saturated: 3.9,
        carbs: 59,
        sugars: 9.6,
        fibre: 7.1,
        protein: 20,
        salt: 2.2
    },
    {
        name: 'Wrap_Philly_Steak',
        calories: 367,
        fat: 7.1,
        saturated: 1.1,
        carbs: 57,
        sugars: 7.1,
        fibre: 4.9,
        protein: 17,
        salt: 1.9
    },
    {
        name: 'Wrap_Taco_Beef',
        calories: 439,
        fat: 16,
        saturated: 5.8,
        carbs: 56,
        sugars: 4.3,
        fibre: 5.6,
        protein: 15,
        salt: 2.2
    },
    {
        name: 'Wrap_Mexicana_Beef_Crunch',
        calories: 610,
        fat: 33,
        saturated: 8.9,
        carbs: 66,
        sugars: 6.3,
        fibre: 7.3,
        protein: 19,
        salt: 3.3
    },
    {
        name: 'Wrap_Garlic_Cheesesteak',
        calories: 624,
        fat: 30,
        saturated: 7.5,
        carbs: 63,
        sugars: 11,
        fibre: 5.9,
        protein: 23,
        salt: 2.8
    },
    {
        name: 'Wrap_Ham',
        calories: 393,
        fat: 11,
        saturated: 3.6,
        carbs: 51,
        sugars: 4.6,
        fibre: 4.9,
        protein: 20,
        salt: 2.4
    },
    {
        name: 'Wrap_Turkey',
        calories: 381,
        fat: 10,
        saturated: 3.1,
        carbs: 50,
        sugars: 4.4,
        fibre: 4.6,
        protein: 21,
        salt: 2.4
    },
    {
        name: 'Wrap_Ham_and_Turkey',
        calories: 415,
        fat: 11,
        saturated: 3.5,
        carbs: 50,
        sugars: 4.8,
        fibre: 4.9,
        protein: 26,
        salt: 2.9
    },
    {
        name: 'Wrap_Spicy_Italian',
        calories: 568,
        fat: 30,
        saturated: 10,
        carbs: 51,
        sugars: 4,
        fibre: 4.6,
        protein: 21,
        salt: 3.8
    },
    {
        name: 'Wrap_Italian_B.M.T',
        calories: 498,
        fat: 23,
        saturated: 7.7,
        carbs: 50,
        sugars: 3.4,
        fibre: 4.4,
        protein: 22,
        salt: 3.3
    },
    {
        name: 'Wrap_Notorious_B.M.T',
        calories: 613,
        fat: 33,
        saturated: 9.9,
        carbs: 53,
        sugars: 5.7,
        fibre: 5.3,
        protein: 25,
        salt: 3.7
    },
    {
        name: 'Wrap_Legendary_Teriyaki',
        calories: 526,
        fat: 17,
        saturated: 6.6,
        carbs: 62,
        sugars: 12,
        fibre: 4.7,
        protein: 29,
        salt: 3.3
    },
    {
        name: 'Wrap_Veggie_Delite',
        calories: 339,
        fat: 9.4,
        saturated: 3,
        carbs: 51,
        sugars: 5.3,
        fibre: 5.1,
        protein: 9.9,
        salt: 1.5
    },
    {
        name: 'Wrap_Cheese_and_Guacamole',
        calories: 396,
        fat: 21,
        saturated: 3.7,
        carbs: 50,
        sugars: 4.1,
        fibre: 4.6,
        protein: 9.7,
        salt: 2
    },
    {
        name: 'Wrap_Tuna_Mayonaise',
        calories: 427,
        fat: 16,
        saturated: 1.6,
        carbs: 51,
        sugars: 4.5,
        fibre: 4.3,
        protein: 19,
        salt: 2.1
    },
    {
        name: 'Wrap_Ulitmate_Festive',
        calories: 516,
        fat: 19,
        saturated: 4.6,
        carbs: 57,
        sugars: 8.3,
        fibre: 4.8,
        protein: 25,
        salt: 2.7
    },
    {
        name: 'Salad_Chicken_Breast',
        calories: 148,
        fat: 4.7,
        saturated: 2.7,
        carbs: 5.3,
        sugars: 4.4,
        fibre: 1.7,
        protein: 20,
        salt: 1.2
    },
    {
        name: 'Salad_Chicken_Tikka',
        calories: 152,
        fat: 5.1,
        saturated: 2.6,
        carbs: 5.6,
        sugars: 3.8,
        fibre: 2.7,
        protein: 22,
        salt: 1.0
    },
    {
        name: 'Salad_Big_Bombay',
        calories: 282,
        fat: 15,
        saturated: 5.2,
        carbs: 13,
        sugars: 11,
        fibre: 3.2,
        protein: 24,
        salt: 1.7
    },
    {
        name: 'Salad_Furious_Chicken',
        calories: 437,
        fat: 31,
        saturated: 6.5,
        carbs: 17,
        sugars: 5.7,
        fibre: 4.1,
        protein: 20,
        salt: 2.5
    },
    {
        name: 'Salad_Rotisserie_Style_Chicken',
        calories: 92,
        fat: 2.1,
        saturated: 0.4,
        carbs: 3.5,
        sugars: 2.7,
        fibre: 1.7,
        protein: 14,
        salt: 0.5
    },
    {
        name: 'Salad_Tex_Mexan',
        calories: 386,
        fat: 23,
        saturated: 6.2,
        carbs: 18,
        sugars: 7.5,
        fibre: 3.8,
        protein: 26,
        salt: 2.1
    },
    {
        name: 'Salad_Honey_Mustard_BBQ_Chicken_And_Bacon',
        calories: 263,
        fat: 13,
        saturated: 5.8,
        carbs: 12,
        sugars: 10,
        fibre: 3.2,
        protein: 22,
        salt: 1.8
    },
    {
        name: 'Salad_Rotisserie_Style_Chicken_and_Guacamole',
        calories: 299,
        fat: 23,
        saturated: 6.4,
        carbs: 10,
        sugars: 6.6,
        fibre: 3.5,
        protein: 20,
        salt: 1.7
    },
    {
        name: 'Salad_Meatball_Marinara_Pork_And_Beef_Meatballs',
        calories: 215,
        fat: 11,
        saturated: 3.2,
        carbs: 14,
        sugars: 8.9,
        fibre: 4.8,
        protein: 14,
        salt: 1.0
    },
    {
        name: 'Salad_Philly_Steak',
        calories: 107,
        fat: 1.5,
        saturated: 0.4,
        carbs: 11,
        sugars: 6.4,
        fibre: 2.6,
        protein: 12,
        salt: 0.7
    },
    {
        name: 'Salad_The_Baller',
        calories: 428,
        fat: 29,
        saturated: 11,
        carbs: 25,
        sugars: 9.4,
        fibre: 4.7,
        protein: 22,
        salt: 2.4
    },
    {
        name: 'Salad_Taco_Beef',
        calories: 172,
        fat: 10.0,
        saturated: 5.1,
        carbs: 9.7,
        sugars: 2.8,
        fibre: 3,
        protein: 9.3,
        salt: 1.0
    },
    {
        name: 'Salad_Mexicana_Beef_Crunch',
        calories: 401,
        fat: 33,
        saturated: 8.6,
        carbs: 21,
        sugars: 6,
        fibre: 4.3,
        protein: 13,
        salt: 2.7
    },
    {
        name: 'Salad_Garlic_Cheesesteak',
        calories: 493,
        fat: 38,
        saturated: 7.8,
        carbs: 20,
        sugars: 12,
        fibre: 3.9,
        protein: 18,
        salt: 1.8
    },
    {
        name: 'Salad_Legendary_Teriyaki',
        calories: 314,
        fat: 14,
        saturated: 6.9,
        carbs: 21,
        sugars: 13,
        fibre: 2.5,
        protein: 23,
        salt: 2.2
    },
    {
        name: 'Salad_Ham',
        calories: 89,
        fat: 2.3,
        saturated: 0.7,
        carbs: 4.8,
        sugars: 3.4,
        fibre: 2.2,
        protein: 12,
        salt: 0.9
    },
    {
        name: 'Salad_Turkey',
        calories: 119,
        fat: 4.5,
        saturated: 2.5,
        carbs: 4.4,
        sugars: 3.5,
        fibre: 1.9,
        protein: 15,
        salt: 1.3
    },
    {
        name: 'Salad_Ham_and_Turkey',
        calories: 135,
        fat: 5.3,
        saturated: 2.7,
        carbs: 4.9,
        sugars: 3.7,
        fibre: 2.1,
        protein: 17,
        salt: 1.4
    },
    {
        name: 'Salad_Spicy_Italian',
        calories: 306,
        fat: 25,
        saturated: 9.7,
        carbs: 5.9,
        sugars: 3.1,
        fibre: 2,
        protein: 16,
        salt: 2.6
    },
    {
        name: 'Salad_Italian_B.M.T',
        calories: 234,
        fat: 17,
        saturated: 7.1,
        carbs: 3.8,
        sugars: 2.2,
        fibre: 2,
        protein: 16,
        salt: 2.2
    },
    {
        name: 'Salad_Notorious_B.M.T',
        calories: 396,
        fat: 31,
        saturated: 9.5,
        carbs: 9.3,
        sugars: 6.1,
        fibre: 3.1,
        protein: 19,
        salt: 2.8
    },
    {
        name: 'Salad_Veggie_Delite',
        calories: 240,
        fat: 7.6,
        saturated: 3.3,
        carbs: 28,
        sugars: 15,
        fibre: 10,
        protein: 10,
        salt: 1.1
    },
    {
        name: 'Salad_Cheese_and_Guacamole',
        calories: 131,
        fat: 15,
        saturated: 3,
        carbs: 3.6,
        sugars: 2.7,
        fibre: 2,
        protein: 4.1,
        salt: 0.8
    },
    {
        name: 'Salad_Tuna_Mayonaise',
        calories: 166,
        fat: 10,
        saturated: 1,
        carbs: 5.9,
        sugars: 3.6,
        fibre: 1.7,
        protein: 13,
        salt: 0.9
    },
    {
        name: 'Salad_Ulitmate_Festive',
        calories: 268,
        fat: 14,
        saturated: 4,
        carbs: 15,
        sugars: 11,
        fibre: 2.2,
        protein: 19,
        salt: 1.6
    },
    {
        name: 'Spud_Butter_And_Cheese324',
        calories: 17,
        fat: 9.9,
        saturated: 51,
        carbs: 2,
        sugars: 7.4,
        fibre: 14,
        protein: 0.7,
        salt: 100
    },
    {
        name: 'Spud_Baked_Beans_And_Cheese',
        calories: 522,
        fat: 17,
        saturated: 9.9,
        carbs: 69,
        sugars: 8.6,
        fibre: 13,
        protein: 21,
        salt: 1.6
    },
    {
        name: 'Spud_Philly_Cheese_Steak_And_Cheese',
        calories: 499,
        fat: 18,
        saturated: 10,
        carbs: 59,
        sugars: 5.9,
        fibre: 8.1,
        protein: 25,
        salt: 1.4
    },
    {
        name: 'Spud_Tuna_Mayo_And_Cheese',
        calories: 558,
        fat: 27,
        saturated: 11,
        carbs: 54,
        sugars: 3,
        fibre: 7.4,
        protein: 26,
        salt: 1.6
    },
    {
        name: 'Spud_B.M.T_And_Cheese',
        calories: 561,
        fat: 27,
        saturated: 13,
        carbs: 53,
        sugars: 2.6,
        fibre: 8,
        protein: 27,
        salt: 2.3
    },
    {
        name: 'Spud_Big_Breakwich',
        calories: 738,
        fat: 37,
        saturated: 16,
        carbs: 69,
        sugars: 6.4,
        fibre: 9.6,
        protein: 32,
        salt: 2.5
    },
    {
        name: 'Spud_Chicken_Breast_And_Cheese',
        calories: 498,
        fat: 18,
        saturated: 10,
        carbs: 53,
        sugars: 3.4,
        fibre: 7.4,
        protein: 30,
        salt: 1.6
    },
    {
        name: 'Spud_Rotisserie_Style_Chicken_And_Cheese',
        calories: 484,
        fat: 19,
        saturated: 10,
        carbs: 51,
        sugars: 2.1,
        fibre: 7.4,
        protein: 27,
        salt: 1.2
    },
    {
        name: 'Spud_Rotisserie_Style_Chicken_with_Guac',
        calories: 601,
        fat: 33,
        saturated: 12,
        carbs: 57,
        sugars: 4.4,
        fibre: 8.6,
        protein: 28,
        salt: 1.8
    },
    {
        name: 'Spud_Furious_Chicken',
        calories: 704,
        fat: 36,
        saturated: 12,
        carbs: 64,
        sugars: 4.6,
        fibre: 9.6,
        protein: 28,
        salt: 2.3
    },
    {
        name: 'Spud_Garlic_Cheese_Steak',
        calories: 667,
        fat: 34,
        saturated: 12,
        carbs: 64,
        sugars: 8.2,
        fibre: 8.8,
        protein: 26,
        salt: 1.7
    },
    {
        name: 'Spud_Ham_And_Cheese',
        calories: 481,
        fat: 19,
        saturated: 10,
        carbs: 53,
        sugars: 2.8,
        fibre: 8,
        protein: 25,
        salt: 1.6
    },
    {
        name: 'Spud_Ham_Turkey_And_Cheese',
        calories: 485,
        fat: 18,
        saturated: 10,
        carbs: 52,
        sugars: 2.8,
        fibre: 7.9,
        protein: 27,
        salt: 1.8
    },
    {
        name: 'Spud_BBQ_Honey_Mustard_Chicken_And_Bacon',
        calories: 577,
        fat: 23,
        saturated: 11,
        carbs: 60,
        sugars: 9.6,
        fibre: 8.4,
        protein: 30,
        salt: 2.1
    },
    {
        name: 'Spud_Meatball_Marinara_And_Cheese',
        calories: 606,
        fat: 27,
        saturated: 13,
        carbs: 61,
        sugars: 8.4,
        fibre: 10,
        protein: 27,
        salt: 1.3
    },
    {
        name: 'Spud_Mexican_Beef',
        calories: 656,
        fat: 37,
        saturated: 14,
        carbs: 67,
        sugars: 4,
        fibre: 10,
        protein: 21,
        salt: 2.2
    },
    {
        name: 'Spud_Spicy_Italian_And_Cheese',
        calories: 656,
        fat: 37,
        saturated: 17,
        carbs: 53,
        sugars: 2.1,
        fibre: 7.7,
        protein: 26,
        salt: 3.0
    },
    {
        name: 'Spud_Chicken_Tikka_And_Cheese',
        calories: 502,
        fat: 18,
        saturated: 10,
        carbs: 53,
        sugars: 2.9,
        fibre: 8.5,
        protein: 32,
        salt: 1.4
    },
    {
        name: 'Spud_Taco_Beef_And_Cheese',
        calories: 524,
        fat: 23,
        saturated: 13,
        carbs: 58,
        sugars: 2,
        fibre: 8.4,
        protein: 20,
        salt: 1.4
    },
    {
        name: 'Spud_Tex_Mexan',
        calories: 620,
        fat: 26,
        saturated: 11,
        carbs: 63,
        sugars: 5.6,
        fibre: 9,
        protein: 32,
        salt: 2.0
    },
    {
        name: 'Spud_Turkey_And_Cheese',
        calories: 469,
        fat: 18,
        saturated: 10,
        carbs: 52,
        sugars: 2.6,
        fibre: 7.7,
        protein: 26,
        salt: 1.7
    },
    {
        name: 'Spud_Avocado_And_Cheese',
        calories: 437,
        fat: 23,
        saturated: 10,
        carbs: 52,
        sugars: 2.4,
        fibre: 8,
        protein: 15,
        salt: 1.0
    },
    {
        name: 'Spud_Coleslaw_And_Chese',
        calories: 577,
        fat: 31,
        saturated: 11,
        carbs: 58,
        sugars: 7.8,
        fibre: 9.6,
        protein: 15,
        salt: 1.3
    },
    {
        name: 'Spud_Veggie_Delite',
        calories: 428,
        fat: 17,
        saturated: 9.9,
        carbs: 54,
        sugars: 4,
        fibre: 8.4,
        protein: 15,
        salt: 0.7
    },
    {
        name: 'Spud_Ulitmate_Festive',
        calories: 611,
        fat: 27,
        saturated: 12,
        carbs: 60,
        sugars: 7.3,
        fibre: 8.3,
        protein: 30,
        salt: 2.0
    },
    {
        name: 'Side_Waffle_Fries_Regular',
        calories: 184,
        fat: 8.2,
        saturated: 1.1,
        carbs: 23,
        sugars: 0.3,
        fibre: 4,
        protein: 2.8,
        salt: 0.9
    },
    {
        name: 'Side_Waffle_Fries_Large',
        calories: 276,
        fat: 12,
        saturated: 1.7,
        carbs: 34,
        sugars: 0.5,
        fibre: 6,
        protein: 4.2,
        salt: 1.3
    },
    {
        name: 'Side_Hash_Browns_6_pieces',
        calories: 184,
        fat: 11,
        saturated: 0.8,
        carbs: 22,
        sugars: 1.1,
        fibre: 2.3,
        protein: 2.4,
        salt: 0.8
    },
    {
        name: 'Side_Nacho_Chicken_Bites_6_Pieces',
        calories: 270,
        fat: 13,
        saturated: 1.8,
        carbs: 21,
        sugars: 1,
        fibre: 1.5,
        protein: 16,
        salt: 1.5
    },
    {
        name: 'Side_Nacho_Chicken_Bites_9_Pieces',
        calories: 405,
        fat: 19,
        saturated: 2.7,
        carbs: 32,
        sugars: 1.4,
        fibre: 2.3,
        protein: 24,
        salt: 2.2
    },
    {
        name: 'Side_Doritos_Lightly_Salted_Nachos',
        calories: 590,
        fat: 30,
        saturated: 10,
        carbs: 60,
        sugars: 5.1,
        fibre: 6.8,
        protein: 19,
        salt: 1.7
    },
    {
        name: 'Side_Doritos_Tangy_Cheese_Nachos',
        calories: 615,
        fat: 34,
        saturated: 11,
        carbs: 55,
        sugars: 6.4,
        fibre: 6,
        protein: 19,
        salt: 2.1
    },
    {
        name: 'Side_Doritos_Chilli_Heat_Wave_Nachos',
        calories: 611,
        fat: 34,
        saturated: 10,
        carbs: 57,
        sugars: 8.8,
        fibre: 5.8,
        protein: 19,
        salt: 2.2
    },
    {
        name: 'Side_Doritos_Lightly_Salted_Nachos_Sharer',
        calories: 868,
        fat: 45,
        saturated: 15,
        carbs: 87,
        sugars: 5.8,
        fibre: 9.6,
        protein: 28,
        salt: 2.3
    },
    {
        name: 'Side_Doritos_Tangy_Cheese_Nachos_Sharer',
        calories: 907,
        fat: 51,
        saturated: 16,
        carbs: 79,
        sugars: 7.8,
        fibre: 8.3,
        protein: 28,
        salt: 3
    },
    {
        name: 'Side_Doritos_Chilli_Heat_Wave_Nachos_Sharer',
        calories: 901,
        fat: 51,
        saturated: 16,
        carbs: 82,
        sugars: 11,
        fibre: 8,
        protein: 28,
        salt: 3.2
    },
    {
        name: 'Side_Footlong_Cheesy_Garlic_Slice',
        calories: 308,
        fat: 18,
        saturated: 9.1,
        carbs: 20,
        sugars: 2.5,
        fibre: 1.1,
        protein: 16,
        salt: 1.1
    },
    {
        name: 'Side_Footlong_Pepperoni_Slice',
        calories: 353,
        fat: 21,
        saturated: 8.8,
        carbs: 25,
        sugars: 5.4,
        fibre: 1.8,
        protein: 18,
        salt: 2.3
    },
    {
        name: 'Side_Footlong_Margherita_Slice',
        calories: 296,
        fat: 15,
        saturated: 8.8,
        carbs: 25,
        sugars: 5.5,
        fibre: 1.6,
        protein: 17,
        salt: 1.2
    },
    {
        name: 'Side_Chipotle_Cheesy_Bites',
        calories: 145,
        fat: 14,
        saturated: 4.7,
        carbs: 16,
        sugars: 1,
        fibre: 1.4,
        protein: 9.8,
        salt: 1.4
    },
    {
        name: 'Side_Footlong_Dipper_Triple_Cheese',
        calories: 450,
        fat: 20,
        saturated: 9.4,
        carbs: 50,
        sugars: 3.6,
        fibre: 3.9,
        protein: 18,
        salt: 2.2
    },
    {
        name: 'Side_Footlong_Dipper_Pepperoni',
        calories: 433,
        fat: 19,
        saturated: 7.3,
        carbs: 49,
        sugars: 3.4,
        fibre: 4,
        protein: 15,
        salt: 2.5
    },
    {
        name: 'Side_Footlong_Dipper_Taco_Beef',
        calories: 430,
        fat: 17,
        saturated: 6.9,
        carbs: 53,
        sugars: 3.3,
        fibre: 4.5,
        protein: 15,
        salt: 2.2
    },
    {
        name: 'Side_Footlong_Dipper_Turkey_And_Stuffing',
        calories: 467,
        fat: 19,
        saturated: 5.6,
        carbs: 53,
        sugars: 4.5,
        fibre: 4.5,
        protein: 19,
        salt: 2.8
    },
    {
        name: 'Side_Sage_and_Onion_Stuffing',
        calories: 70,
        fat: 5.4,
        saturated: 0.4,
        carbs: 4.2,
        sugars: 0.8,
        fibre: 0.4,
        protein: 0.4,
        salt: 0.4
    }
].map((item) => ({
    ...item,
    proteinToCalRatio: item.protein / (item.calories || 1),
    carbToCalRatio: item.carbs / (item.calories || 1)
}))
