// Snapshot of the KFC UK menu, captured by hand. This is a point-in-time copy:
// it can (and will) go stale as KFC changes its menu or reformulates items.
// Re-capture from KFC's published nutrition data to refresh.
//
// `updatedAt` is the date this snapshot was last hand-captured. Bump it (ISO
// YYYY-MM-DD) whenever you refresh the data below — the web app reads it to
// show a "last updated / stale" badge.
export const updatedAt = '2025-09-01'

export default [
    {
        item: 'REGULAR FRIES',
        serving_size: '1',
        kJ: 1096,
        Kcal: 261,
        fat_g: 9.78,
        saturated_fat_g: 0.8,
        carbohydrates_g: 38,
        sugars_g: 0.5,
        protein_g: 3.1,
        salt_g: 0.74
    },
    {
        item: 'LARGE FRIES',
        serving_size: '1',
        kJ: 1539,
        Kcal: 367,
        fat_g: 14,
        saturated_fat_g: 1.09,
        carbohydrates_g: 53,
        sugars_g: 0.5,
        protein_g: 4.3,
        salt_g: 1
    },
    {
        item: 'DIRTY LOUISIANA FRIES',
        serving_size: '1',
        kJ: 2031,
        Kcal: 483,
        fat_g: 24,
        saturated_fat_g: 2,
        carbohydrates_g: 53,
        sugars_g: 5.49,
        protein_g: 12.9,
        salt_g: 1.7
    },
    {
        item: 'REGULAR COLESLAW',
        serving_size: '1',
        kJ: 619,
        Kcal: 150,
        fat_g: 13,
        saturated_fat_g: 1,
        carbohydrates_g: 6.1,
        sugars_g: 5.3,
        protein_g: 1.1,
        salt_g: 0.57
    },
    {
        item: 'LARGE COLESLAW',
        serving_size: '1',
        kJ: 1235,
        Kcal: 299,
        fat_g: 26,
        saturated_fat_g: 2,
        carbohydrates_g: 12,
        sugars_g: 11,
        protein_g: 2.2,
        salt_g: 1.1
    },
    {
        item: 'CORN COBETTE',
        serving_size: '1',
        kJ: 240,
        Kcal: 57,
        fat_g: 1.3,
        saturated_fat_g: 0.2,
        carbohydrates_g: 8.1,
        sugars_g: 1.9,
        protein_g: 2.2,
        salt_g: 0.01
    },
    {
        item: 'HASHBROWN (PER PIECE AVERAGE)',
        serving_size: 'per piece average',
        kJ: 381,
        Kcal: 92,
        fat_g: 5.5,
        saturated_fat_g: 0.2,
        carbohydrates_g: 8.8,
        sugars_g: 0.7,
        protein_g: 0.9,
        salt_g: 0.55
    },
    {
        item: 'LARGE SIGNATURE FRIES',
        serving_size: '1',
        kJ: 1559,
        Kcal: 372,
        fat_g: 14,
        saturated_fat_g: 1.1,
        carbohydrates_g: 54,
        sugars_g: 0.5,
        protein_g: 4.4,
        salt_g: 1
    },
    {
        item: 'REGULAR SIGNATURE FRIES',
        serving_size: '1',
        kJ: 1069,
        Kcal: 261,
        fat_g: 9.8,
        saturated_fat_g: 0.79,
        carbohydrates_g: 38,
        sugars_g: 0.49,
        protein_g: 3.1,
        salt_g: 0.74
    },
    {
        item: '2 CORN COBETTES (LARGE)',
        serving_size: '1',
        kJ: 481,
        Kcal: 115,
        fat_g: 2.7,
        saturated_fat_g: 0.4,
        carbohydrates_g: 16,
        sugars_g: 3.8,
        protein_g: 4.4,
        salt_g: 0.01
    },
    {
        item: 'REGULAR CREAMY MASH',
        serving_size: '1',
        kJ: 523,
        Kcal: 124,
        fat_g: 3.4,
        saturated_fat_g: 2.1,
        carbohydrates_g: 20,
        sugars_g: 1,
        protein_g: 2.4,
        salt_g: 0.88
    },
    {
        item: 'SIDE SALAD',
        serving_size: '1',
        kJ: 232,
        Kcal: 56,
        fat_g: 3.6,
        saturated_fat_g: 0.3,
        carbohydrates_g: 4.7,
        sugars_g: 2.09,
        protein_g: 0.8,
        salt_g: 0.2
    },
    {
        item: 'LARGE CREAMY MASH',
        serving_size: '1',
        kJ: 1045,
        Kcal: 248,
        fat_g: 6.8,
        saturated_fat_g: 4.3,
        carbohydrates_g: 40,
        sugars_g: 2,
        protein_g: 4.8,
        salt_g: 1.8
    },
    {
        item: 'KENTUCKY MAYO TWISTER',
        serving_size: '1',
        kJ: 2189,
        Kcal: 523,
        fat_g: 24,
        saturated_fat_g: 4,
        carbohydrates_g: 46,
        sugars_g: 5.1,
        protein_g: 29,
        salt_g: 2.6
    },
    {
        item: 'SWEET CHILLI TWISTER',
        serving_size: '1',
        kJ: 2086,
        Kcal: 497,
        fat_g: 18,
        saturated_fat_g: 4.4,
        carbohydrates_g: 53,
        sugars_g: 11,
        protein_g: 29,
        salt_g: 2.6
    },
    {
        item: 'SMOKEY BBQ TWISTER',
        serving_size: '1',
        kJ: 2014,
        Kcal: 479,
        fat_g: 17,
        saturated_fat_g: 4.43,
        carbohydrates_g: 51,
        sugars_g: 8.8,
        protein_g: 29,
        salt_g: 2.4
    },
    {
        item: "FLAMIN' MINI WRAP",
        serving_size: '1',
        kJ: 1401,
        Kcal: 335,
        fat_g: 16,
        saturated_fat_g: 2.6,
        carbohydrates_g: 28.99,
        sugars_g: 2.9,
        protein_g: 18,
        salt_g: 1.1
    },
    {
        item: 'SUPERCHARGER TWISTER',
        serving_size: '1',
        kJ: 2263,
        Kcal: 541,
        fat_g: 26,
        saturated_fat_g: 5.1,
        carbohydrates_g: 46,
        sugars_g: 5.7,
        protein_g: 29,
        salt_g: 2.6
    },
    {
        item: 'BBQ MINI WRAP',
        serving_size: '1',
        kJ: 1250,
        Kcal: 298,
        fat_g: 11,
        saturated_fat_g: 2.2,
        carbohydrates_g: 30.99,
        sugars_g: 4.6,
        protein_g: 18,
        salt_g: 1.1
    },
    {
        item: 'KENTUCKY ORIGINAL WRAP',
        serving_size: '1',
        kJ: 2110,
        Kcal: 505,
        fat_g: 23.88,
        saturated_fat_g: 2.92,
        carbohydrates_g: 44.82,
        sugars_g: 3.44,
        protein_g: 28.53,
        salt_g: 2.52
    },
    {
        item: 'ORIGINAL RECIPE CHICKEN KEEL',
        serving_size: '1',
        kJ: 921,
        Kcal: 220,
        fat_g: 11,
        saturated_fat_g: 1.9,
        carbohydrates_g: 6.8,
        sugars_g: 0.5,
        protein_g: 23,
        salt_g: 0.94
    },
    {
        item: 'ORIGINAL RECIPE CHICKEN DRUMSTICK',
        serving_size: '1',
        kJ: 750,
        Kcal: 179,
        fat_g: 10,
        saturated_fat_g: 1.5,
        carbohydrates_g: 8,
        sugars_g: 0.5,
        protein_g: 14,
        salt_g: 0.74
    },
    {
        item: 'ORIGINAL RECIPE CHICKEN THIGH',
        serving_size: null,
        kJ: 1116,
        Kcal: 268,
        fat_g: 17,
        saturated_fat_g: 3.4,
        carbohydrates_g: 8.2,
        sugars_g: 0.2,
        protein_g: 20,
        salt_g: 1
    },
    {
        item: 'ORIGINAL RECIPE CHICKEN RIB',
        serving_size: '1',
        kJ: 1296,
        Kcal: 310,
        fat_g: 15,
        saturated_fat_g: 2.5,
        carbohydrates_g: 11,
        sugars_g: 0.5,
        protein_g: 33.1,
        salt_g: 1.31
    },
    {
        item: 'ORIGINAL RECIPE CHICKEN WING',
        serving_size: '1',
        kJ: 762,
        Kcal: 182,
        fat_g: 10.3,
        saturated_fat_g: 1.7,
        carbohydrates_g: 6.8,
        sugars_g: 0.5,
        protein_g: 16,
        salt_g: 0.67
    },
    {
        item: 'SMALL POPCORN CHICKEN',
        serving_size: '1',
        kJ: 592,
        Kcal: 142,
        fat_g: 8.3,
        saturated_fat_g: 0.8,
        carbohydrates_g: 8.29,
        sugars_g: 0.2,
        protein_g: 8.3,
        salt_g: 0.64
    },
    {
        item: 'REGULAR POPCORN CHICKEN',
        serving_size: '1',
        kJ: 1283,
        Kcal: 307,
        fat_g: 18,
        saturated_fat_g: 1.8,
        carbohydrates_g: 17.99,
        sugars_g: 0.5,
        protein_g: 18,
        salt_g: 1.3
    },
    {
        item: 'LARGE POPCORN CHICKEN',
        serving_size: '1',
        kJ: 1996,
        Kcal: 478,
        fat_g: 28,
        saturated_fat_g: 2.8,
        carbohydrates_g: 28,
        sugars_g: 0.6,
        protein_g: 28,
        salt_g: 2.2
    },
    {
        item: 'HOT WING (PER PIECE, AVERAGE)',
        serving_size: '1',
        kJ: 380,
        Kcal: 91,
        fat_g: 6.2,
        saturated_fat_g: 0.9,
        carbohydrates_g: 3.8,
        sugars_g: 0.5,
        protein_g: 4.9,
        salt_g: 0.35
    },
    {
        item: 'MINI FILLET (PER PIECE, AVERAGE)',
        serving_size: '1',
        kJ: 5522,
        Kcal: 124,
        fat_g: 5.5,
        saturated_fat_g: 0.59,
        carbohydrates_g: 5.8,
        sugars_g: 0.5,
        protein_g: 13,
        salt_g: 0.87
    },
    {
        item: 'KANSAS BBQ DIPPED BITES',
        serving_size: '1',
        kJ: 1463,
        Kcal: 349,
        fat_g: 14,
        saturated_fat_g: 1.6,
        carbohydrates_g: 33.99,
        sugars_g: 15,
        protein_g: 21,
        salt_g: 1.6
    },
    {
        item: 'SWEET CHILLI DIPPED BITES',
        serving_size: '1',
        kJ: 1588,
        Kcal: 378,
        fat_g: 15,
        saturated_fat_g: 1.6,
        carbohydrates_g: 39,
        sugars_g: 22.99,
        protein_g: 21,
        salt_g: 1.6
    },
    {
        item: 'FILLET BURGER',
        serving_size: '1',
        kJ: 1900,
        Kcal: 455,
        fat_g: 19.2,
        saturated_fat_g: 2.3,
        carbohydrates_g: 44.8,
        sugars_g: 6,
        protein_g: 29.6,
        salt_g: 2.54
    },
    {
        item: 'ZINGER BURGER',
        serving_size: '1',
        kJ: 1915,
        Kcal: 420,
        fat_g: 17.6,
        saturated_fat_g: 2,
        carbohydrates_g: 40.9,
        sugars_g: 5.8,
        protein_g: 25.8,
        salt_g: 1.98
    },
    {
        item: 'FILLET TOWER BURGER',
        serving_size: '1',
        kJ: 2520,
        Kcal: 605,
        fat_g: 28,
        saturated_fat_g: 4.8,
        carbohydrates_g: 58.1,
        sugars_g: 10.7,
        protein_g: 33.4,
        salt_g: 3.91
    },
    {
        item: 'ZINGER SUPERCHARGER TOWER BURGER',
        serving_size: '1',
        kJ: 2580,
        Kcal: 615,
        fat_g: 32.9,
        saturated_fat_g: 5,
        carbohydrates_g: 52.4,
        sugars_g: 8.4,
        protein_g: 29.6,
        salt_g: 3.4
    },
    {
        item: 'MINI FILLET BURGER',
        serving_size: '1',
        kJ: 1164,
        Kcal: 277,
        fat_g: 10,
        saturated_fat_g: 1.09,
        carbohydrates_g: 27.99,
        sugars_g: 2.59,
        protein_g: 18,
        salt_g: 1.4
    },
    {
        item: 'ZINGER STACKER',
        serving_size: '1',
        kJ: 3135,
        Kcal: 750,
        fat_g: 36.1,
        saturated_fat_g: 7.8,
        carbohydrates_g: 56.9,
        sugars_g: 12.7,
        protein_g: 50.9,
        salt_g: 4.5
    },
    {
        item: 'CHICKEN FILLET ROLL (ROI ONLY)',
        serving_size: '1',
        kJ: 2793,
        Kcal: 665,
        fat_g: 25,
        saturated_fat_g: 5.2,
        carbohydrates_g: 77.99,
        sugars_g: 7.49,
        protein_g: 29,
        salt_g: 3.2
    },
    {
        item: 'ZINGER FILLET ROLL (ROI ONLY)',
        serving_size: '1',
        kJ: 3146,
        Kcal: 751,
        fat_g: 36,
        saturated_fat_g: 6,
        carbohydrates_g: 81,
        sugars_g: 9,
        protein_g: 23,
        salt_g: 3.3
    },
    {
        item: 'VEGAN BURGER',
        serving_size: '1',
        kJ: 1690,
        Kcal: 405,
        fat_g: 17.7,
        saturated_fat_g: 1.5,
        carbohydrates_g: 43.4,
        sugars_g: 7.2,
        protein_g: 16.4,
        salt_g: 2.67
    },
    {
        item: 'CHEESY TOWER BURGER',
        serving_size: '1',
        kJ: 2620,
        Kcal: 624,
        fat_g: 23,
        saturated_fat_g: 5.4,
        carbohydrates_g: 67,
        sugars_g: 12,
        protein_g: 35,
        salt_g: 4.1
    },
    {
        item: 'DIRTY LOUISIANA BURGER',
        serving_size: '1',
        kJ: 2913,
        Kcal: 696,
        fat_g: 35,
        saturated_fat_g: 5.2,
        carbohydrates_g: 61,
        sugars_g: 10.99,
        protein_g: 32,
        salt_g: 3.8
    },
    {
        item: 'BBQ FILLET TOWER BURGER',
        serving_size: '1',
        kJ: 2550,
        Kcal: 610,
        fat_g: 28.1,
        saturated_fat_g: 4.8,
        carbohydrates_g: 59.6,
        sugars_g: 11,
        protein_g: 33.3,
        salt_g: 3.8
    }
].map((item) => ({
    ...item,
    name: item.item,
    calories: item.Kcal,
    protein: item.protein_g,
    fat: item.fat_g,
    carbs: item.carbohydrates_g,
    proteinToCalRatio: item.protein_g / (item.Kcal || 1),
    carbToCalRatio: item.carbohydrates_g / (item.Kcal || 1)
}))
