// Snapshot of the Wendy's UK menu, captured by hand. This is a point-in-time
// copy: it can (and will) go stale as Wendy's changes its menu or reformulates
// items. Re-capture from Wendy's published nutrition data to refresh.
//
// `updatedAt` is the date this snapshot was last hand-captured. Bump it (ISO
// YYYY-MM-DD) whenever you refresh the data below — the web app reads it to
// show a "last updated / stale" badge.
export const updatedAt = '2025-09-01'

export default [
    {
        'Menu Item': "Wendy's Single",
        calories: 524,
        fat: 29,
        saturated: 10,
        carbs: 37,
        sugars: 8.2,
        fibre: 1.7,
        protein: 28,
        salt: 2.2
    },
    {
        'Menu Item': "Wendy's Double",
        calories: 879,
        fat: 56,
        saturated: 22,
        carbs: 39,
        sugars: 9.7,
        fibre: 1.7,
        protein: 54,
        salt: 4.4
    },
    {
        'Menu Item': "Wendy's Triple",
        calories: 1195,
        fat: 80,
        saturated: 33,
        carbs: 41,
        sugars: 10,
        fibre: 1.7,
        protein: 77,
        salt: 6.1
    },
    {
        'Menu Item': 'Baconator',
        calories: 1001,
        fat: 66,
        saturated: 26,
        carbs: 38,
        sugars: 8.5,
        fibre: 1.7,
        protein: 63,
        salt: 5.8
    },
    {
        'Menu Item': 'Jr. Cheeseburger Deluxe',
        calories: 366,
        fat: 19,
        saturated: 6.3,
        carbs: 31,
        sugars: 7.3,
        fibre: 1.4,
        protein: 17,
        salt: 1.9
    },
    {
        'Menu Item': 'Jr. Bacon Cheeseburger',
        calories: 410,
        fat: 23,
        saturated: 7.4,
        carbs: 30,
        sugars: 5.9,
        fibre: 1.4,
        protein: 20,
        salt: 2.3
    },
    {
        'Menu Item': 'Sweet N Smokey Cheeseburger Single',
        calories: 847,
        fat: 51,
        saturated: 18,
        carbs: 51,
        sugars: 15,
        fibre: 2.1,
        protein: 45,
        salt: 4.1
    },
    {
        'Menu Item': 'Sweet N Smokey Cheeseburger Double',
        calories: 1210,
        fat: 78,
        saturated: 30,
        carbs: 52,
        sugars: 15,
        fibre: 2.1,
        protein: 74,
        salt: 5.4
    },
    {
        'Menu Item': 'Sweet N Smokey Cheeseburger Triple',
        calories: 1622,
        fat: 110,
        saturated: 44,
        carbs: 53,
        sugars: 16,
        fibre: 2.1,
        protein: 104,
        salt: 7.1
    },
    {
        'Menu Item': 'Spicy Chicken',
        calories: 400,
        fat: 15,
        saturated: 2.4,
        carbs: 45,
        sugars: 6.3,
        fibre: 2.4,
        protein: 20,
        salt: 2.2
    },
    {
        'Menu Item': 'Classic Chicken',
        calories: 404,
        fat: 15,
        saturated: 2.5,
        carbs: 46,
        sugars: 6.4,
        fibre: 2.5,
        protein: 20,
        salt: 2.5
    },
    {
        'Menu Item': 'Grilled Chicken',
        calories: 337,
        fat: 10,
        saturated: 1.2,
        carbs: 35,
        sugars: 6.4,
        fibre: 1.7,
        protein: 26,
        salt: 1.6
    },
    {
        'Menu Item': 'Avocado Chicken Club',
        calories: 583,
        fat: 30,
        saturated: 8.7,
        carbs: 47,
        sugars: 6.5,
        fibre: 2.4,
        protein: 30,
        salt: 3.4
    },
    {
        'Menu Item': '4 Pc Chicken Nuggets',
        calories: 114,
        fat: 5.6,
        saturated: 1.4,
        carbs: 4.9,
        sugars: 0,
        fibre: 0,
        protein: 11,
        salt: 0.93
    },
    {
        'Menu Item': '6 Pc Chicken Nuggets',
        calories: 173,
        fat: 8.4,
        saturated: 2.1,
        carbs: 7.4,
        sugars: 0,
        fibre: 0,
        protein: 17,
        salt: 1.4
    },
    {
        'Menu Item': '10 Pc Chicken Nuggets',
        calories: 286,
        fat: 14,
        saturated: 3.4,
        carbs: 12,
        sugars: 0,
        fibre: 0,
        protein: 28,
        salt: 2.3
    },
    {
        'Menu Item': '20 Pc Chicken Nuggets',
        calories: 572,
        fat: 28,
        saturated: 6.9,
        carbs: 25,
        sugars: 0,
        fibre: 0,
        protein: 55,
        salt: 4.6
    },
    {
        'Menu Item': '4 Pc Spicy Chicken Nuggets',
        calories: 99,
        fat: 2.8,
        saturated: 0.5,
        carbs: 6.5,
        sugars: 0,
        fibre: 0,
        protein: 12,
        salt: 0.37
    },
    {
        'Menu Item': '6 Pc Spicy Chicken Nuggets',
        calories: 152,
        fat: 4.1,
        saturated: 0.8,
        carbs: 9.8,
        sugars: 0,
        fibre: 0,
        protein: 19,
        salt: 0.55
    },
    {
        'Menu Item': '10 Pc Spicy Chicken Nuggets',
        calories: 250,
        fat: 6.8,
        saturated: 1.3,
        carbs: 16,
        sugars: 0,
        fibre: 0.6,
        protein: 31,
        salt: 0.92
    },
    {
        'Menu Item': '20 Pc Spicy Chicken Nuggets',
        calories: 499,
        fat: 13,
        saturated: 2.6,
        carbs: 33,
        sugars: 0,
        fibre: 1.2,
        protein: 62,
        salt: 1.8
    },
    {
        'Menu Item': '6 Pc Buffalo Saucy Classic Nuggets',
        calories: 189,
        fat: 9.7,
        saturated: 2.2,
        carbs: 8.3,
        sugars: 0.7,
        fibre: 0,
        protein: 17,
        salt: 4.3
    },
    {
        'Menu Item': '10 Pc Buffalo Saucy Classic Nuggets',
        calories: 312,
        fat: 16,
        saturated: 3.6,
        carbs: 14,
        sugars: 0.9,
        fibre: 0,
        protein: 28,
        salt: 6.1
    },
    {
        'Menu Item': '6 Pc Buffalo Saucy Spicy Nuggets',
        calories: 169,
        fat: 5.4,
        saturated: 0.9,
        carbs: 11,
        sugars: 0.7,
        fibre: 0,
        protein: 19,
        salt: 3.4
    },
    {
        'Menu Item': '10 Pc Buffalo Saucy Spicy Nuggets',
        calories: 276,
        fat: 8.8,
        saturated: 1.5,
        carbs: 18,
        sugars: 1,
        fibre: 0.6,
        protein: 31,
        salt: 4.7
    },
    {
        'Menu Item': '6 Pc BBQ Saucy Classic Nuggets',
        calories: 255,
        fat: 9.5,
        saturated: 2.2,
        carbs: 25,
        sugars: 16,
        fibre: 0.7,
        protein: 17,
        salt: 2.9
    },
    {
        'Menu Item': '10 Pc BBQ Saucy Classic Nuggets',
        calories: 382,
        fat: 16,
        saturated: 3.6,
        carbs: 31,
        sugars: 18,
        fibre: 0.8,
        protein: 28,
        salt: 3.9
    },
    {
        'Menu Item': '6 Pc BBQ Saucy Spicy Nuggets',
        calories: 233,
        fat: 5.2,
        saturated: 0.9,
        carbs: 27,
        sugars: 16,
        fibre: 1.1,
        protein: 19,
        salt: 2
    },
    {
        'Menu Item': '10 Pc BBQ Saucy Spicy Nuggets',
        calories: 347,
        fat: 8.5,
        saturated: 1.5,
        carbs: 35,
        sugars: 18,
        fibre: 1.4,
        protein: 32,
        salt: 2.5
    },
    {
        'Menu Item': 'Sweet N Smokey Chicken Sandwich',
        calories: 627,
        fat: 29,
        saturated: 6.3,
        carbs: 62,
        sugars: 14,
        fibre: 2.8,
        protein: 28,
        salt: 3.8
    },
    {
        'Menu Item': 'Sweet N Smokey Grilled Chicken Sandwich',
        calories: 529,
        fat: 21,
        saturated: 4.8,
        carbs: 50,
        sugars: 14,
        fibre: 2.1,
        protein: 34,
        salt: 3.1
    },
    {
        'Menu Item': 'Sweet N Smokey Spicy Chicken Sandwich',
        calories: 610,
        fat: 28,
        saturated: 6.2,
        carbs: 61,
        sugars: 14,
        fibre: 2.8,
        protein: 27,
        salt: 3.8
    },
    {
        'Menu Item': 'BBQ Wrap w/ Halloumi Fries',
        calories: 365,
        fat: 19,
        saturated: 8.4,
        carbs: 33,
        sugars: 7.9,
        fibre: 2.8,
        protein: 14,
        salt: 1.8
    },
    {
        'Menu Item': 'Signature Wrap w/ Halloumi Fries',
        calories: 435,
        fat: 29,
        saturated: 9.2,
        carbs: 28,
        sugars: 3.6,
        fibre: 2.8,
        protein: 14,
        salt: 1.8
    },
    {
        'Menu Item': 'Avocado Wrap w/ Halloumi Fries',
        calories: 359,
        fat: 21,
        saturated: 7.2,
        carbs: 29,
        sugars: 4.2,
        fibre: 2.8,
        protein: 12,
        salt: 1.5
    },
    {
        'Menu Item': 'BBQ Wrap w/ Halloumi Fries (Duo Wrap)',
        calories: 729,
        fat: 38,
        saturated: 17,
        carbs: 66,
        sugars: 16,
        fibre: 5.6,
        protein: 28,
        salt: 3.6
    },
    {
        'Menu Item': 'Signature Wrap w/ Halloumi Fries (Duo Wrap)',
        calories: 869,
        fat: 58,
        saturated: 18,
        carbs: 56,
        sugars: 7.3,
        fibre: 5.6,
        protein: 28,
        salt: 3.5
    },
    {
        'Menu Item': 'Avocado Wrap w/ Halloumi Fries (Duo Wrap)',
        calories: 704,
        fat: 41,
        saturated: 14,
        carbs: 57,
        sugars: 8.4,
        fibre: 5.6,
        protein: 24,
        salt: 3
    },
    {
        'Menu Item': 'Curry Mayo Wrap w/ Crispy Chicken',
        calories: 301,
        fat: 16,
        saturated: 3.1,
        carbs: 28,
        sugars: 2.6,
        fibre: 2.5,
        protein: 10,
        salt: 1.2
    },
    {
        'Menu Item': 'Avocado Wrap w/ Grilled Chicken',
        calories: 223,
        fat: 8.8,
        saturated: 2.3,
        carbs: 22,
        sugars: 2.2,
        fibre: 2,
        protein: 13,
        salt: 0.78
    },
    {
        'Menu Item': 'Avocado Wrap w/ Classic Chicken',
        calories: 260,
        fat: 11,
        saturated: 2.9,
        carbs: 28,
        sugars: 2.1,
        fibre: 2.3,
        protein: 11,
        salt: 1.1
    },
    {
        'Menu Item': 'Avocado Wrap w/ Spicy Chicken',
        calories: 252,
        fat: 11,
        saturated: 2.9,
        carbs: 27,
        sugars: 2.1,
        fibre: 2.3,
        protein: 10,
        salt: 1.1
    },
    {
        'Menu Item': 'Signature Wrap w/ Grilled Chicken',
        calories: 301,
        fat: 17,
        saturated: 4.3,
        carbs: 21,
        sugars: 1.6,
        fibre: 2,
        protein: 15,
        salt: 1
    },
    {
        'Menu Item': 'Signature Wrap w/ Classic Chicken',
        calories: 341,
        fat: 20,
        saturated: 5,
        carbs: 27,
        sugars: 1.5,
        fibre: 2.3,
        protein: 12,
        salt: 1.3
    },
    {
        'Menu Item': 'Signature Wrap w/ Spicy Chicken',
        calories: 341,
        fat: 20,
        saturated: 4.9,
        carbs: 27,
        sugars: 1.5,
        fibre: 2.3,
        protein: 12,
        salt: 1.3
    },
    {
        'Menu Item': 'BBQ Wrap w/ Grilled Chicken',
        calories: 235,
        fat: 7.4,
        saturated: 3.5,
        carbs: 26,
        sugars: 5.9,
        fibre: 2,
        protein: 15,
        salt: 1
    },
    {
        'Menu Item': 'BBQ Wrap w/ Classic Chicken',
        calories: 269,
        fat: 9.8,
        saturated: 4.1,
        carbs: 32,
        sugars: 5.8,
        fibre: 2.3,
        protein: 12,
        salt: 1.4
    },
    {
        'Menu Item': 'BBQ Wrap w/ Spicy Chicken',
        calories: 268,
        fat: 9.7,
        saturated: 4.1,
        carbs: 32,
        sugars: 5.8,
        fibre: 2.3,
        protein: 12,
        salt: 1.4
    },
    {
        'Menu Item': 'Caesar Salad',
        calories: 317,
        fat: 29,
        saturated: 6.2,
        carbs: 3.9,
        sugars: 3.5,
        fibre: 1.4,
        protein: 9.4,
        salt: 1.4
    },
    {
        'Menu Item': 'Avocado Salad',
        calories: 399,
        fat: 35,
        saturated: 9.1,
        carbs: 7.2,
        sugars: 5,
        fibre: 1.4,
        protein: 13,
        salt: 1.4
    },
    {
        'Menu Item': 'Caesar Chicken Salad',
        calories: 411,
        fat: 31,
        saturated: 6.6,
        carbs: 4.2,
        sugars: 3.7,
        fibre: 1.4,
        protein: 28,
        salt: 2.1
    },
    {
        'Menu Item': 'Avocado Chicken Salad',
        calories: 485,
        fat: 36,
        saturated: 9.5,
        carbs: 7.5,
        sugars: 5.2,
        fibre: 1.4,
        protein: 32,
        salt: 2.2
    },
    {
        'Menu Item': 'Caesar Salad w/ Halloumi Fries',
        calories: 499,
        fat: 42,
        saturated: 12,
        carbs: 11,
        sugars: 5.6,
        fibre: 2.3,
        protein: 18,
        salt: 2.3
    },
    {
        'Menu Item': 'Avocado Salad w/ Halloumi Fries',
        calories: 567,
        fat: 47,
        saturated: 14,
        carbs: 14,
        sugars: 7.1,
        fibre: 2.2,
        protein: 21,
        salt: 2.5
    },
    {
        'Menu Item': 'Value Fries',
        calories: 142,
        fat: 6.7,
        saturated: 0.5,
        carbs: 18,
        sugars: 3.5,
        fibre: 1.5,
        protein: 1.6,
        salt: 2.1
    },
    {
        'Menu Item': 'Regular Fries',
        calories: 176,
        fat: 8.5,
        saturated: 0.6,
        carbs: 22,
        sugars: 3.7,
        fibre: 1.9,
        protein: 2,
        salt: 2.1
    },
    {
        'Menu Item': 'Large Fries',
        calories: 239,
        fat: 11,
        saturated: 0.8,
        carbs: 31,
        sugars: 6.8,
        fibre: 2.6,
        protein: 2.7,
        salt: 2.4
    },
    {
        'Menu Item': 'Baconator Fries',
        calories: 459,
        fat: 34,
        saturated: 9.3,
        carbs: 25,
        sugars: 2.6,
        fibre: 2.3,
        protein: 12,
        salt: 1.7
    },
    {
        'Menu Item': 'Cheesy Topped Fries',
        calories: 351,
        fat: 24,
        saturated: 7.1,
        carbs: 25,
        sugars: 2.5,
        fibre: 2.3,
        protein: 7.5,
        salt: 2.6
    },
    {
        'Menu Item': 'Plain Potato',
        calories: 232,
        fat: 5.4,
        saturated: 3.4,
        carbs: 39,
        sugars: 2.4,
        fibre: 4.7,
        protein: 4.4,
        salt: 1.9
    },
    {
        'Menu Item': 'Bacon & Cheese Potato',
        calories: 405,
        fat: 20,
        saturated: 8.4,
        carbs: 40,
        sugars: 3.8,
        fibre: 4.3,
        protein: 14,
        salt: 1.6
    },
    {
        'Menu Item': 'Sour Cream and Chives Potato',
        calories: 233,
        fat: 5.4,
        saturated: 3.3,
        carbs: 39,
        sugars: 3.4,
        fibre: 4.4,
        protein: 4.9,
        salt: 0.04
    },
    {
        'Menu Item': 'Chili',
        calories: 253,
        fat: 13,
        saturated: 5.5,
        carbs: 14,
        sugars: 3.5,
        fibre: 1.9,
        protein: 19,
        salt: 1.5
    },
    {
        'Menu Item': 'Chili Cheese Fries',
        calories: 481,
        fat: 31,
        saturated: 9.8,
        carbs: 32,
        sugars: 4.2,
        fibre: 3.2,
        protein: 17,
        salt: 1.7
    },
    {
        'Menu Item': 'Chili Cheese Baked Potato',
        calories: 428,
        fat: 17,
        saturated: 9,
        carbs: 47,
        sugars: 5.5,
        fibre: 5.3,
        protein: 19,
        salt: 1.6
    },
    {
        'Menu Item': 'Halloumi Fries',
        calories: 178,
        fat: 13,
        saturated: 5.1,
        carbs: 6.6,
        sugars: 2.1,
        fibre: 0.9,
        protein: 8.2,
        salt: 1.1
    },
    {
        'Menu Item': "Kid's Cheeseburger",
        calories: 317,
        fat: 14,
        saturated: 5.8,
        carbs: 30,
        sugars: 6.3,
        fibre: 1.4,
        protein: 17,
        salt: 1.8
    },
    {
        'Menu Item': "Kid's Hamburger",
        calories: 278,
        fat: 11,
        saturated: 4.3,
        carbs: 29,
        sugars: 5.5,
        fibre: 1.4,
        protein: 15,
        salt: 1.3
    },
    {
        'Menu Item': '4 Pc Chicken Nuggets',
        calories: 114,
        fat: 5.6,
        saturated: 1.4,
        carbs: 4.9,
        sugars: 0,
        fibre: 0,
        protein: 11,
        salt: 0.93
    },
    {
        'Menu Item': 'Small Hashbrown',
        calories: 194,
        fat: 12,
        saturated: 1.3,
        carbs: 19,
        sugars: 0,
        fibre: 2,
        protein: 1.4,
        salt: 0.73
    },
    {
        'Menu Item': 'Regular Hashbrown',
        calories: 271,
        fat: 16,
        saturated: 1.8,
        carbs: 28,
        sugars: 0,
        fibre: 3.1,
        protein: 2.1,
        salt: 1.1
    },
    {
        'Menu Item': 'Large Hashbrown',
        calories: 356,
        fat: 21,
        saturated: 2.4,
        carbs: 37,
        sugars: 0,
        fibre: 4,
        protein: 2.7,
        salt: 1.5
    },
    {
        'Menu Item': '6 Pc Mini Donuts',
        calories: 321,
        fat: 16,
        saturated: 7.2,
        carbs: 39,
        sugars: 17,
        fibre: 1.7,
        protein: 4.4,
        salt: 1.1
    },
    {
        'Menu Item': 'Patty',
        calories: 122,
        fat: 9.3,
        saturated: 4.1,
        carbs: 0,
        sugars: 0,
        fibre: 0,
        protein: 9.5,
        salt: 0.06
    },
    {
        'Menu Item': 'Large Patty',
        calories: 273,
        fat: 21,
        saturated: 9.2,
        carbs: 0,
        sugars: 0,
        fibre: 0,
        protein: 21,
        salt: 0.13
    },
    {
        'Menu Item': 'Bacon 2 Pieces',
        calories: 42,
        fat: 3.2,
        saturated: 1.2,
        carbs: 0,
        sugars: 0,
        fibre: 0,
        protein: 3.3,
        salt: 0.48
    },
    {
        'Menu Item': 'Bacon 3 Pieces',
        calories: 63,
        fat: 4.8,
        saturated: 1.8,
        carbs: 0,
        sugars: 0,
        fibre: 0,
        protein: 4.9,
        salt: 0.72
    },
    {
        'Menu Item': 'Sausage',
        calories: 158,
        fat: 13,
        saturated: 4.6,
        carbs: 1.5,
        sugars: 0.7,
        fibre: 0,
        protein: 8.8,
        salt: 0.39
    }
].map((item) => ({
    ...item,
    name: item['Menu Item'],
    proteinToCalRatio: item.protein / (item.calories || 1),
    carbToCalRatio: item.carbs / (item.calories || 1)
}))
